- utils/error.js
`Error.captureStackTrace` was unavailable in our react-native app. It did not cause a compile error but, rather it failed at runtime with the error:
`Error.captureStackTrace is not a function. In 'Error.captureStackTrace(t,t.constructor)', 'Error.captureStackTrace' is undefined`
Node Version: 6.6.0
> Guard against unavailable captureStackTrace

- index.js
Looks like this got missed. Made it impossible to getUser info
> Fix options not found error

- android/src/main/java/com/auth0/react/A0Auth0Package.java
React Native v0.47.0 removes the createJSModules call, so this @Override now breaks the build.
```
:react-native-code-push:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/Luke/Projects/ClientPOC/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java:305: error: method does not override or implement a method from a supertype
@Override
^
```
Confirmed this change fixes the build.  See RN Breaking Changes in the v0.47.0 release: https://github.com/facebook/react-native/releases/tag/v0.47.0
See also identical change e.g. in react-native-code-push: https://github.com/Microsoft/react-native-code-push/pull/895/commits/dff9f47a4b8b31e9ad4bfe36acf57fff8291163d
> Remove override annotation on createJSModules method

- android/src/main/java/com/auth0/react/A0Auth0Module.java
- auth/__tests__/__snapshots__/index.spec.js.snap
- auth/__tests__/index.spec.js
- auth/index.js
- ios/A0Auth0.m
- webauth/agent.js
- webauth/index.js
> Added clearSession iOS Safari Method

- android/build.gradle
This change fixes an issue several adopters are running into: "Could not invoke A0Auth.showUrl".  See: https://github.com/auth0/react-native-auth0/issues/67#issuecomment-322209597
Fixes #67
> Change customtabs version to the same as default build tools

- android/src/main/java/com/auth0/react/A0Auth0Module.java
> Close Browser app tab after finishing Auth

- android/src/main/java/com/auth0/react/A0Auth0Module.java
See https://github.com/auth0/react-native-auth0/issues/83
Changes from review.
> Fixed race condition in callback when using React Native Navigation

- android/src/main/java/com/auth0/react/A0Auth0Module.java
I want to clarify how each flow works:
CustomTabs are meant to be open within the app. The NEW_TASK flag should not be used on that case. Of course I wasn't aware of this behavior until we required to pause the activity to get some data from an external app, like gmail.
For the Browser intent logic, which is only used in the case of calling `showUrl` from a non-activity class, the NEW_TASK flag is required as the context used is the Application one instead of the Activity one. If this flag is not provided a runtime exception raises. Browser is "still used" when going through the CustomTabs logic and no CustomTabs compatible browser app is installed in the device.
The NO_HISTORY flag introduced in a previous commit to avoid leaving the browser app in the "recents app" view doesn't work as …
> Fix android web authentication

- README.md
- android/build.gradle
React Native projects with multiple native dependencies often end up unintentionally relying on a variety of Android SDK versions, which can lead to unpredictable build-time failures or even run-time crashes, such as the weirdness in #67. Many libraries (see, e.g., react-community/react-native-maps#2047, invertase/react-native-firebase#1007) have been moving to a system of allowing the solution [recommended by google](https://developer.android.com/studio/build/gradle-tips.html#configure-project-wide-properties) of having the root project set properties with the desired dependency versions. This PR implements that solution for `react-native-auth0`.
> android: allow root project to specify dependency versions

- webauth/index.js
Auth0.js use webAuth.authorize({connection: "facebook"}) to support social login, but react-native-auth0 didn't document this parameter, so I added it to help others to know it
> Update webAuth documentation 

- ios/A0Auth0.m
In RN 0.49+ the following warning appears 
```Module A0Auth0 requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.```
This implements the requiresMainQueueSetup method and returns `true`.
> Add requiresMainQueueSetup to fix warning in RN 0.49+

- A0Auth0.podspec
The React pod is deprecated and, since React Native already requires React, we should remove this dependency from A0Auth0.podspec.
This resolves issue #191 .
With Auth0 for React Native installed, simply attempt to `pod install` from the `ios/` directory in an ejected app that uses CocoaPods. This pod and all other pods should successfully install.
> Remove obsolete React dependency from podspec.

- ios/A0Auth0.m
- webauth/agent.js
Adds support for iOS 11 SFAuthenticationSession & iOS 12 ASWebAuthenticationSession
This enables SSO in iOS 11+
No changes are required by the developer, all is handled internally.
> Added iOS SF/ASWeb AuthenticationSession support

- A0Auth0.podspec
Restore the `react` dependency in Podspec
Fixes #207 
> Podspec restore react dependency

- webauth/__mocks__/auth0.js
- webauth/__mocks__/react-native.js
- webauth/__tests__/webauth.spec.js
- webauth/index.js
This PR enables the clear session feature for Android and fixes it for iOS.
When this is merged, it will **always** send the `client_id` and the `returnTo` parameters when opening the Auth0 logout URL. 
Devs would need to whitelist the `returnTo` URL in the "Allowed Logout URLs" section of their **application's settings** in the Auth0 dashboard. Fail to do so will show an error page when the redirect is attempted.
```js
auth0.webAuth
.clearSession({})
.then(success => {
//Logged out!
})
.catch(error => {
//Browser closed by the user.
});
```
At first, seems to only affect _iOS only_ (because Android was disabled!). But if we look deeper, the current behavior is to open the logout URL without passing any `returnTo` nor `clientId` values. Testing this in an iOS simulator resulted in a …
> Enable WebAuth Logout for Android & Fix iOS Logout.

- webauth/index.js
The error handling for the WebAuth controller was wrong. Should be using the `AuthError` instead of a generic `Auth0Error` class.
https://github.com/auth0/react-native-auth0/issues/220
Manual testing only.
> Fix error handling by using authentication error class

- ios/A0Auth0.m
Added support for iOS 13 behaviour changes in Web Authentication
#233 
N/A
> Added support for iOS 13 Web Authentication changes

- android/build.gradle
Update the `build.gradle` script to stop using `javaCompile` instruction that was deprecated a while ago and soon to be removed.
resolves https://github.com/auth0/react-native-auth0/issues/264
> Fix gradle javaCompile warning

- src/jwt/__tests__/jwt.spec.js
- src/jwt/signatureVerifier.js
Added a missing use case in which the public key the SDK requires can't be found
> Handle missing kid (key id) on the JWKS

- README.md
- src/auth/__tests__/__snapshots__/index.spec.js.snap
- src/auth/__tests__/index.spec.js
- src/auth/index.js
This PR adds support for invoking the new passwordless endpoints. It also adds a small note on the readme about them and the grant type that must be enabled first.
There are some UX changes on the second request (the one that performs the authentication). The endpoint expects a `username` parameter, but I'm mapping it from either `email` or `phoneNumber`. The same happens with `otp`, which is getting mapped from `code`. Please, evaluate if this is desired or if it's only adding noise.
> Any formatting change included on the diff is due to the pre-commit hook.
`SDK-1281`
I've tested the email passwordless manually on a sample app. Unit tests are included as well.
> Add passwordless endpoints

- src/auth/__tests__/__snapshots__/index.spec.js.snap
- src/auth/__tests__/index.spec.js
- src/auth/index.js
- Added the [Token Exchange for Native Social](https://auth0.com/docs/api/authentication#token-exchange-for-native-social) endpoint to the Auth API
- Closes https://github.com/auth0/react-native-auth0/issues/254
> Added token exchange for native social endpoint [SDK-1307]

- src/auth/authError.js
Updated ```AuthError``` class to return invalid_token error from www-authenticate header. Error caused when using an expired token.
issue #241  
Manual testing only
This was just a quick fix to get it working for my project, happy to take feedback and change my approach to this.
> handle invalid token error

- ios/A0Auth0.podspec
The `Podspec` was not referencing correctly the version tag, because the tags in this repo are prefixed with `v`.
Closes https://github.com/auth0/react-native-auth0/issues/293
> Fixed tag in Podspec

- README.md
- ios/A0Auth0.m
- src/webauth/__mocks__/auth0.js
- src/webauth/__tests__/agent.spec.js
- src/webauth/agent.js
- src/webauth/index.js
- Added a new boolean parameter called `ephemeralSession` to the `options` object that sets `prefersEphemeralWebBrowserSession` to `true` on iOS 13+. It has no effect on older versions of iOS, or on Android. **Usage of this method disables SSO.**
Closes https://github.com/auth0/react-native-auth0/issues/294
This change was tested manually by performing login and logout on iOS and Android.
> Added support for ephemeral sessions [SDK-1412]

- .circleci/config.yml
- yarn.lock
- Bumps the dependency versions respecting the package.json file contents.
- Changes the CI script Node version from 8 to LTS
> Bump dependencies in the lock file

- README.md
- android/build.gradle
- package.json
- yarn.lock
This PR bumps most dependencies to their latest version.
It also upgrades the minimum required react-native version from 0.60.5 to 0.62.2. This is in response to `CVE-2020-8149`.
- AndroidX Browser to 1.2.0
- React to +16.11.0
- React-Native to +0.62.2
- Logkitty to +0.7.1
https://github.com/advisories/GHSA-v8v8-6859-qxm4
No additional tests were required. I will be updating the sample app soon.
> Breaking: Require ReactNative version 0.62.2

- README.md
- src/webauth/index.js
In order to improve DX when the Application ID (android) or Bundle Identifier (iOS) values have uppercase characters, a warning will be printed to the device console. This warning only appears on the non-production environment according to the react-native docs.
**This is just a warning! The authorize call will go through regardless of the bundle identifier value.**
The warning message is the following:
`
"The Bundle Identifier or Application ID of your app contains uppercase characters and will be lowercased to build the Callback URL. Check the Auth0 dashboard to whitelist the right URL value."
`
This PR also rephrases the callback URLs section of the README. (feedback?)
React native docs about warnings https://reactnative.dev/docs/debugging#warnings
Resolves …
> Warn when bundle identifier contains uppercase characters

- android/build.gradle
This fixes gradle builds with a minSdkVersion lower than 24
Added `compileOptions` entry to `android/build.gradle`.
#322
See reproduction guide in #322
> Add compileOptions for JDK 8

- src/auth/__tests__/__snapshots__/index.spec.js.snap
- src/auth/__tests__/index.spec.js
- src/auth/authError.js
The header object is a special list that must be accessed with `get(name)`, otherwise, there are certain `cors` [scenarios](https://developers.google.com/web/updates/2015/03/introduction-to-fetch#response_types) where not all the headers would be exposed.
This PR handles the possibility of that header not being set and ensures the last fallback is also test-covered.
https://github.com/auth0/react-native-auth0/pull/285 introduced a change that wasn't properly tested
> Fix the www-authenticate header parsing logic

- README.md
This PR adds guidance was added to the README regarding how to handle the `requires_verification` error returned when the [Bot Protection](https://auth0.com/docs/anomaly-detection/bot-protection) feature is enabled and a login/sign up request is flagged as suspicious.
The code snippet was tested manually for both login and signup on the React Native [sample app](https://github.com/auth0-samples/auth0-react-native-sample).
> Add Bot Protection guidance to README [SDK-1898]

- README.md
This PR updates an outdated iOS snippet in the README that featured a now-deprecated method.
Fixes https://github.com/auth0/react-native-auth0/issues/343.
> Updated iOS snippet in the README

- README.md
- src/webauth/__tests__/webauth.spec.js
- src/webauth/index.js
The Bundle Identifier / Application ID might contain characters not allowed in a URL scheme. This PR adds support for specifying a custom scheme to be used instead.
> Added support for using a custom scheme in the callback URL [SDK-2223]

- README.md
- src/jwt/__tests__/jwt.spec.js
- src/jwt/validator.js
- src/webauth/__tests__/__snapshots__/webauth.spec.js.snap
- src/webauth/__tests__/webauth.spec.js
- src/webauth/index.js
This PR adds support for organizations. It consists of two new setters added to the webauth module.
Pass the `invitationUrl` parameter to the `webAuth.authorize` method to allow the user to accept an invitation. The given URL will be parsed and the required values extracted and used when the browser is launched.
If the organization ID is known, pass the `organization` parameter to the `webAuth.authorize` method to allow the user to log in to an organization.
> When logging in into an organization, the received ID token will contain an `org_id` claim that will be automatically verified against the organization id requested when the authentication was started.
See `SDK-2398`
> Add support for Organizations [SDK-2398]

- ios/A0Auth0.m
Since version 12.5 (released on 26 Apr 2021), Xcode no longer accepts an entire URL for the `ASWebAuthenticationSession` scheme value. This PR extracts the scheme from the URL and uses just that, instead of the whole `/authorize` URL.
Fixes #360
> Fix for Xcode 12.5 [SDK-2545]

- README.md
This PR adds information to the README about performing logout on iOS when the `ephemeralSession` parameter is being used.
> Add ephemeral session information to the README

- package.json
React is a peer dependency of this package. This PR adds React 17 to the semver range in the `package.json` so it can be used with the latest version of React Native without forcing install with `npm i --force`.
> Add React 17 to the package.json semver range

- README.md
This PR expands the README instructions for migrating to the SDK version [v2.9.0](https://github.com/auth0/react-native-auth0/releases/tag/v2.9.0) that contains an Android breaking change.
In particular, a link is provided to the respective commit of the React Native sample app, as an example of the changes to make.
And a couple of paragraphs were added with instructions for those who are not using Web Authentication.
Related to https://github.com/auth0/react-native-auth0/pull/350
> Update Android migration instructions

- README.md
This PR adds a note to the README about the need to set up the manifest placeholders differently when using flavors with different application ID values.
From https://github.com/auth0/react-native-auth0/issues/392
> Add a note to the README about manifest placeholders when using flavors

- src/auth/__tests__/__snapshots__/index.spec.js.snap
- src/auth/__tests__/index.spec.js
- src/auth/index.js
Please describe both what is changing and why this is important. Include:
- modify the auth refreshToken call to allow custom parameters
Please include relevant links supporting this change such as a:
- from Issue #385 
> Disable whitelist on auth refreshToken call (#385)

- README.md
- android/build.gradle
- package.json
- yarn.lock
This PR updates the Gradle configuration to support Gradle 7, which is used since React Native 0.65.
Fixes https://github.com/auth0/react-native-auth0/issues/422
The changes have been tested with the sample app, upgraded to React Native 0.67.0-rc.3:
> Add support for Gradle 7 [SDK-2964]

- src/webauth/__mocks__/linking.js
- src/webauth/agent.js
Fixed the failing test in #411
#410 Warning caused because of using removeListener method
#411 The test failed since the mock object didn't have the required methods
> Fix: Warning on RN65 while linking from agent.js

- src/webauth/agent.js
Please describe both what is changing and why this is important. Include:
- We have added a null check to ensure if old versions of RN uses our library (which is incompatible) we still provide compatibility in removing the event listener
Manually tested for older versions of RN just to be sure. The recent versions can be tested using the unit test
> Fix - Provide backward compatibility to remove event subscription

- README.md
- src/auth/__tests__/__snapshots__/index.spec.js.snap
- src/auth/__tests__/index.spec.js
- src/auth/index.js
Implemented APIs to use MFA Login with OTP, OOB, Using recovery code and requesting MFA Challenge
New methods added to the public API - loginWithOTP, loginWithOOB, loginWithRecoveryCode, multifactorChallenge
Information on how to use this has been added to the README file as well
I have added required unit tests and did manual testing to all the features as well. I have tested this with Android platform. Since this runs on JS, the iOS platform behaviour should be same. But never the less manual testing will be done for iOS as well
> Feature: Implemented MFA APIs

- android/build.gradle
Please describe both what is changing and why this is important. Include:
androidJavadoc task which isn't used in the project blocked users from integrating the SDK for Gradle 7. We have fixed this by replacing deprecated functionality
https://docs.gradle.org/current/userguide/java_plugin.html#tab:configurations
The SDK has been tested in the latest React Native and Gradle versions as well as the older ones ( RN 0.66.4 & Gradle 6~)
> Fix android java doc task

- src/webauth/__tests__/agent.spec.js
- src/webauth/agent.js
When using Web Auth, after the native code calls the RN callback with an error or the redirect URL, the javascript code checks those values and either rejects or resolves a promise. But the code was not handling the case when both error and redirect URL are null, which can happen on iOS under particular circumstances (e.g. retrying the Web Auth login immediately after it failed).
This PR handles that case by rejecting the promise with an error.
Fixes https://github.com/auth0/react-native-auth0/issues/460
A unit test was added for this scenario, and also it was tested manually on iOS 15.4 (iPhone simulator), using React Native `0.66.4`.
> Fix promise that never completes [SDK-3216]

- ios/A0Auth0.h
- ios/A0Auth0.m
>From https://github.com/expo/expo/issues/15622#issuecomment-997225774, the double-quoted react header imports will break building on Expo SDK 44. The double-quoted imports should be for react-native < 0.40. as nowadays react-native uses CocoaPods, it should be safe to use the angle-bracket import.
> Fix iOS module import for Expo SDK 44

- android/build.gradle
React Native v0.69 has been released recently and it is breaking our build for Android due to unused documentation tasks. We are removing these tasks to avoid breakage while importing the library.
https://github.com/auth0/react-native-auth0/issues/486
We have tested it with sample application, newly initialized application and demo applications reported in the GH issue
> [SDK-3458] Support RN version 69

- A0Auth0.podspec
- android/build.gradle
- android/src/main/java/com/auth0/react/A0Auth0Module.java
- android/src/main/java/com/auth0/react/CredentialsParser.java
- index.js
- ios/A0Auth0-Bridging-Header.h
- ios/A0Auth0.h
- ios/A0Auth0.m
- ios/A0Auth0.xcodeproj/project.pbxproj
- ios/CredentialsManagerBridge.swift
- src/credentials-manager/__tests__/credentials-manager.spec.js
- src/credentials-manager/credentialsManagerError.js
- src/credentials-manager/index.js
We have provided Credentials Manager support for Android and iOS in React Native. The following methods are added
- getCredentials
- saveCredentials
- hasValidCredentials
- clearCredentials
We also return a boolean value from Android API for `clearCredentials`. This is to be same to our iOS API and Flutter API
This PR is a superset of https://github.com/auth0/react-native-auth0/pull/497 and will have all the changes and reviews from there implemented.
https://github.com/auth0/react-native-auth0/issues/476
> [SDK-3537] Credential manager for React Native

- README.md
Borrowed heavily from [the Flutter credentials manager docs](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#credentials-manager).
> [SDK-3542] Add Credentials Manager documentation to the readme

- package.json
- yarn.lock
React Native released support for React 18. So projects using React 18 will throw warning when our SDK is added.
This doesn't require any change from our end except adding support at package.json
https://github.com/auth0/react-native-auth0/issues/495
Tested manually with a react-native 0.69.5 & react 18
> Update peer dependency for React

- .circleci/config.yml
Created a new build job for the `vnext` branch and override `publish-command` so that it uses a tag.
> ci: publish vnext with tag

- .circleci/config.yml
- package.json
We will use this PR to test whether the latest version of Ship Orb avoids the breakage in CI.
We are adding `dry-run` argument to avoid uploading to the NPM registry.
The version is updated so that the CI will not fail because similar version already exists in NPM.
If this succeeds, we will clean up and remove the `vnext` job and run this only on master
> Test latest version of Ship orb

- src/auth/index.js
This allows passing all available parameters to the [signup endpoint](https://auth0.com/docs/api/authentication#signup).
This resolves #352  
You can pass additional parameters to the [createUser method](https://auth0.github.io/react-native-auth0/Auth.html#.createUser), such as `name`
> Add remaining fields for signing up a user

- src/hooks/__tests__/use-auth0.spec.js
- src/hooks/auth0-provider.js
- yarn.lock
This change means that `openid profile email` scope is always passed to the call to `authorize()` when using the hook. Futhermore, care is taken to ensure duplicate scopes are not passed even if the developer specifies them themselves.
> [SDK-3658] Default scopes for authorize call (hooks only)

- .circleci/config.yml
- package.json
As tested in PR #520 
The version of Ship Orb used did not work for custom publish commands. Though we are not using custom publish command now, this caused an issue when we were releasing beta. To avoid this we have updated the version of Ship Orb used.
https://github.com/auth0/react-native-auth0/pull/520
> [SDK-3659] Fix CI to latest version of Ship Orb

- android/src/main/AndroidManifest.xml
We have removed Activities from Auth0.Android library being added to the RNA manifest. This being added caused to open a prompt with asking to choose the sample application twice. 
These activities are noted in the manifest to be removed
There was an issue noting this here - https://github.com/auth0/react-native-auth0/issues/531
We have manually tested this.
We used this command `adb shell dumpsys package r` which previously showed 2 activities registered to receive the intent. Now there will be just 1 which will avoid the above issue
> Removed Activity from Android library to avoid prompt

- src/auth/__tests__/__snapshots__/index.spec.js.snap
- src/auth/__tests__/index.spec.js
- src/auth/index.js
This PR changes the argument verification in `auth.passwordRealm` to not ignore unknown options so that it's possible to pass through extra parameters in the request for use in rules
> [SDK-3718] Allow passing extra parameters when logging in with passwordRealm

- android/src/main/AndroidManifest.xml
We have avoided config changes by locking them in the Manifest. The analysis for this is already done and the related Android ticket with PR is linked below
How this fixed issue in Android - https://github.com/auth0/Auth0.Android/issues/530
Issue reported in RNA - https://github.com/auth0/Auth0.Android/issues/530
We have tested this manually as Unit test is not really possible here
> Avoid config changes to handle authentication

- src/hooks/__tests__/use-auth0.spec.js
- src/hooks/auth0-provider.js
- We have passed the options parameter to underlying `authorize` call
- We have added tests to avoid this regression in future
GH Issue - https://github.com/auth0/react-native-auth0/issues/539
PR - https://github.com/auth0/react-native-auth0/pull/540/
- Added Unit tests
- Manually tested if ephemeral sessions are working
Thanks to [@ebg](https://github.com/ebg1223) for filing this issue and providing a fix through PR. We couldn't use that one due to additional changes which is something we will be considering adding as well.
> [SDK-3736] Fix: Options Parameter not being passed in Hooks `authorize` method

- src/hooks/__tests__/use-auth0.spec.js
- src/hooks/auth0-context.js
- src/hooks/auth0-provider.js
- src/hooks/use-auth0.js
Added an option in Hooks `clearSession` to clear credentials only in Credential Manager and not in the web session. It throws an error if both `federated` and `credentialsManagerOnly`  is enabled
The JS Doc handling for this is a not quite great after trying multiple ways. Any suggestion on improving this would be great.
This is a feature request from this PR - https://github.com/auth0/react-native-auth0/pull/540
We have added unit tests
> [SDK-3738] Option to clear session only in Credentials Manager

- A0Auth0.podspec
This PR adds support for using the library with `use_frameworks! :linkage => :static` on iOS.
Fixes #528
The changes were tested manually with React Native 0.70.3, Xcode 14.1 (14B47b), using an iPhone 14 simulator running iOS 16.1.
> Add support for static linking on iOS

- src/hooks/auth0-provider.js
[WebAuth:authorize](https://github.com/auth0/react-native-auth0/blob/master/src/webauth/index.js#L70) expects `(parameters, options)`. [useAuth0:authorize](https://github.com/auth0/react-native-auth0/blob/master/src/hooks/auth0-provider.js#L65) expects `(options, parameters)`
Confusingly `useAuth0:authorize` passes the variables flipped to `WebAuth:authorize`
```javascript
// Function is paraphrased to make the point clear
authorize = (options, parameters) => {
client.webAuth.authorize(options, parameters);
};
```
This PR fixes this confusion by renaming the variables to their proper names.
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new …
> Fixed `useAuth0:authorize` parameter names

- ios/CredentialsManagerBridge.swift
You can only return JSON primitives over the bridge, the Foundation Date comes back as `null` for this reason.
Look at the credentials returned from `CredentialsManager` via the bridge.
```js
const auth = new Auth0(...) 
auth.credentialsManager.getCredentials().then(console.log)
```
> Return a unix timestamp for expiresIn

- src/auth/__tests__/__snapshots__/index.spec.js.snap
- src/auth/__tests__/index.spec.js
- src/auth/index.js
Allows sending custom parameters in login methods
This request has been raised internally many times. Other SDKs support custom parameters
> Enable custom params for login methods

- package.json
- yarn.lock
This PR bumps the dependencies lockfile `yarn.lock` to address Snyk security warnings.
See internal Snyk dashboard.
> Security: Bump Dependencies

- ios/A0Auth0.m
Currently calling `.hide()` on iOS only works on pre iOS pre 11.
Pre iOS 11 the library is presenting the authentication webview using `presentingViewController`. On iOS 11 `SFSafariViewController` is used though, an on iOS 12 and up we're using `ASWebAuthenticationSession`.
This PR is implementing the required changes to close the authentication webview on iOS 11 and up.
> Fixing `.hide()` on iOS

- yarn.lock
This PR updates the `yarn.lock` file dependencies to resolve security warnings.
N/A
N/A
> chore: Bump `yarn.lock` dependencies

- README.md
- src/hooks/__tests__/use-auth0.spec.js
- src/hooks/auth0-context.js
- src/hooks/auth0-provider.js
- src/hooks/reducer.js
- src/hooks/use-auth0.js
Add `isInitializing` flag to `useAuth0`. This is true until we know that a user is either logged in or logged out. This allows us to prevent showing the logged in or logged out state of an app incorrectly while the `user` is returned from the `CredentialsManager`. 
```js
const MyComponent = () => {
const { isInitializing, user } = useAuth0();
if (isInitializing) {
return <Text>Auth0 is initializing</Text>;
}
return <Text>User is logged { user ? 'in' : 'out' }</Text>;
}
```
> Initialized flag on useAuth0 hook

- android/src/main/java/com/auth0/react/A0Auth0Module.java
`requireAuthentication` method in Android if executed before `onStart` uses activity results API which needs to be run on main thread. If not run on main thread it throws an exception. To avoid this edge case we will execute the method on main thread
https://github.com/auth0/react-native-auth0/issues/589
> Run requireAuth on UI thread

- docs/credentials-manager_index.js.html
- src/credentials-manager/index.js
Strategy is a param of requireLocalAuthentication function that is actually a Number, but, is described as a String in the docs
This is my first PR here, let me know if I missed anything please. 
- Changed comments above requireLocalAuthentication
- Changed html of requireLocalAuthentication
Please include relevant links supporting this change such as a:
- If you take a look at LocalAuthenticationStrategy enum, you will see that those values are indeed numbers instead of strings.
There's no functional changes at all, just docs.
> Fixing comments & docs regarding requireLocalAuthentication "strategy" param

- EXAMPLES.md
- README.md
With this documentation change, we are making custom scheme mandatory. This is due to the reason that Expo uses the application ID or bundle identifier we use to as the scheme to open the application. This shows a popup when the login is done successfully and choosing the wrong option could break the application flow.
For this reason we have made custom scheme as mandatory for Expo application and added guidance on how to do it.
This will change in the next major where we will generate the scheme for callback URL with `auth0` prefixed to the package name to avoid clash with Expo
Issues were raised because of this 
https://github.com/auth0/react-native-auth0/issues/582
https://github.com/auth0/react-native-auth0/issues/606
PR in samples - …
> Make custom scheme mandatory for Expo

- android/src/main/java/com/auth0/react/A0Auth0Module.java
- android/src/main/java/com/auth0/react/AuthenticationActivity.java
Currently when a browser is not available in Android, the issue is not surfaced and instead it gets engulfed. To fix this issue we have added a check to result code to check whether browser is not found.
The error written [here](https://github.com/auth0/react-native-auth0/blob/master/android/src/main/java/com/auth0/react/A0Auth0Module.java#L160) doesn't seem to be raised
https://github.com/auth0/react-native-auth0/issues/340
> [ESD-27178] Fix browser not found issue not being surfaced

- README.md
Fixes the login example in the README: https://github.com/auth0/react-native-auth0#login
The README erroneously instructs using the `clearSession()` method for login instead of `authorize()`.
> Corrects login example in README

- android/build.gradle
- android/src/main/java/com/auth0/react/A0Auth0Module.java
- src/credentials-manager/__tests__/credentials-manager.spec.js
- src/credentials-manager/index.ts
- src/hooks/__tests__/use-auth0.spec.jsx
- src/hooks/auth0-context.ts
- src/hooks/auth0-provider.tsx
- yarn.lock
This PR adds support for `forceRefresh` on Android (iOS pending in a separate PR).
Also, Android version was upgraded to 31 and `useAndroidX` specific in Gradle settings.
> [SDK-4299] Support forceRefresh in Android (without Android config changes)

- A0Auth0.podspec
Using dynamic pod version to fetch the latest version of the JWTDecode and SimpleKeychain SDK seems to break RNA. We have used fixed version because of this
https://github.com/auth0/react-native-auth0/issues/646
> Fix Auth0.Swift transitive dependencies

- package.json
- plugin/src/generateCode.ts
- plugin/src/withAuth0.ts
- yarn.lock
We are updating Expo to version 48. This will remove "@expo/config-plugin" as our dependency and just use Expo as a `peerDependency` and `devDependency`.
Since we migrate to proper Expo module, we are not able to use some internal APIs and we have forked them as recommended
https://docs.expo.dev/config-plugins/development-and-debugging/#install-dependencies
https://github.com/auth0/react-native-auth0/issues/563
> [SDK-3885] Expo plugin update

- BREAKING-CHANGE.md
- plugin/src/__tests__/__snapshots__/withAuth0-test.ts.snap
- plugin/src/withAuth0.ts
- src/credentials-manager/index.ts
- src/internal-types.ts
- src/types.ts
- src/webauth/__tests__/agent.spec.js
- src/webauth/agent.ts
- src/webauth/index.ts
- Add `.auth0` suffix to end of scheme in callback URL to be unique from the callback URL used in frameworks like Expo.
- Provide `useLegacyCallbackUrl` option for non Expo users who don't want to migrate
⚠️ Breaking Change
We are migrating the callback URL we use in the SDK. Please follow the steps in BREAKING-CHANGE.md. Following flow chart shows an idea on how to go ahead with the migration
The new callback URLs are 
```
iOS: {PRODUCT_BUNDLE_IDENTIFIER}.auth0://{DOMAIN}/ios/{PRODUCT_BUNDLE_IDENTIFIER}/callback
Android: {YOUR_APP_PACKAGE_NAME}.auth0://{DOMAIN}/android/{YOUR_APP_PACKAGE_NAME}/callback
```
https://github.com/auth0/react-native-auth0/pull/610
> [SDK-3881] Fix expo scheme clash issue

- scripts/jsdocs.js
This PR fixes the docs build:
- publishes from the correct source folder `out/` as opposed to `out/react-native-auth0/{version}`
- uses the correct NPM script name `docs`
This was tested manually to verify correctness.
> chore: fix docs build script

- src/hooks/__tests__/use-auth0.spec.jsx
- src/hooks/auth0-context.ts
- src/hooks/auth0-provider.tsx
The authorize methods currently doesn't return the credentials and instead we have to call `getCredentials`. This is unwanted call and inefficient to access file system when the credentials are already present. To handle this we return `Credentials` in all the authorize methods
https://github.com/auth0/react-native-auth0/pull/640
> [SDK-4365] Return credentials for authorize methods

- android/src/main/java/com/auth0/react/A0Auth0Module.java
- example/android/app/build.gradle
- example/ios/Auth0Example/Info.plist
- ios/A0Auth0.m
- ios/NativeBridge.swift
- src/internal-types.ts
- src/webauth/__tests__/agent.spec.js
- src/webauth/agent.ts
- iOS doesn't automatically pick up the scheme change similar to Android and it has to be set as a parameter in `redirectURL`. This has been achieved in this change. 
- Example app has new schemes implemented
> Add redirect URL to iOS login - new scheme changes

- package.json
[Full Changelog](https://github.com/auth0/react-native-auth0/compare/v2.17.4...v3.0.0-beta.1)
💡 Check the [Migration Guide](MIGRATION_GUIDE.md) to understand the changes required to migrate your application to v3.
**Added**
- Credentials are returned as part of authorize methods in hooks
- Added sample app in the repository
- Expo plugin is updated to latest version
- Added 'openid profile email' as mandatory scopes
- Option to `forceRefresh` is added in `getCredentials`
- Added `hasValidCredentials` to hooks
- More options to authorize using Hooks
- `authorizeWithSMS`
- `authorizeWithEmail`
- `authorizeWithOOB`
- `authorizeWithOTP`
- `authorizeWithRecoveryCode`
**Changed**
- Custom Scheme is now optional in Expo
- Migrated the codebase to Typescript
- Use Native SDKs …
> Release v3.0.0-beta.1

- .circleci/config.yml
- CHANGELOG.md
[Full Changelog](https://github.com/auth0/react-native-auth0/compare/v2.17.4...v3.0.0-beta.2)
💡 Check the [Migration Guide](MIGRATION_GUIDE.md) to understand the changes required to migrate your application to v3.
**Added**
- Credentials are returned as part of authorize methods in hooks
- Added sample app in the repository
- Expo plugin is updated to latest version
- Added 'openid profile email' as mandatory scopes
- Option to `forceRefresh` is added in `getCredentials`
- Added `hasValidCredentials` to hooks
- More options to authorize using Hooks
- `authorizeWithSMS`
- `authorizeWithEmail`
- `authorizeWithOOB`
- `authorizeWithOTP`
- `authorizeWithRecoveryCode`
**Changed**
- Custom Scheme is now optional in Expo
- Migrated the codebase to Typescript
- Use Native SDKs …
> Release v3.0.0 beta.2

- src/index.ts
- tsconfig.build.json
- tsconfig.json
- We are exporting all the external types through root now.
- Typescript currently packages some of the unwanted files in the package. Previous exclude didn't work as `tsconfig.build.json` overrides it
- The path refers to root package
https://github.com/auth0/react-native-auth0/issues/675
> Export types as part of root

- .semgrepignore
This PR expands the `.semgrepignore` manifest file to exclude test-related directories to avoid triggering false positives.
> chore: Expand `.semgrepignore` exclusions to tests

- A0Auth0.podspec
- android/build.gradle
This PR checks for (org_name) claim when organisation parameter is used with Organisation Name instead of Organisation ID.
https://github.com/auth0/Auth0.Android/pull/669
https://github.com/auth0/Auth0.swift/pull/782
> [SDK-4416] Support Organisation Name

- example/ios/Podfile.lock
- ios/NativeBridge.swift
This issue is occuring since web authentication returns `timeIntervalSince1970` but save credentials used `timeIntervalSinceNow`. This is fixed in this change.
https://github.com/auth0/react-native-auth0/issues/684
Tested the changes manually
> Fix `expiresIn` in iOS has an incorrect value

- MIGRATION_GUIDE.md
- android/src/main/java/com/auth0/react/CredentialsParser.java
- ios/NativeBridge.swift
- src/auth/__tests__/__snapshots__/index.spec.js.snap
- src/auth/__tests__/index.spec.js
- src/auth/index.ts
- src/credentials-manager/__tests__/credentials-manager.spec.js
- src/credentials-manager/index.ts
- src/internal-types.ts
- src/types.ts
- src/utils/__tests__/__snapshots__/timestampConversion.spec.js.snap
- src/utils/__tests__/timestampConversion.spec.js
- src/utils/timestampConversion.ts
We are changing all use of `expiresIn` to `expiresAt` as a UNIX timestamp to make it consistent. These changes are done in the API client as well. This will avoid confusions and use proper naming convention and we will use the major release as an opportunity to make this change.
https://github.com/auth0/react-native-auth0/issues/684
Manual testing done in Android and iOS as well
> Rename expires in to expires at

- example/src/App.tsx
- src/hooks/auth0-context.ts
The types are having mandatory parameters for `authorize` and `clearSession`. We have fixed this by making them optional as it should be.
https://github.com/auth0/react-native-auth0/issues/700
> Make `authorize` and `clearSession` parameters optional

- FAQ.md
- MIGRATION_GUIDE.md
The documentation and migration guide has missed out on mentioning that there is a breaking change in how we get custom parameters as an input in the `authorize` method. This has been updated
https://github.com/auth0/react-native-auth0/issues/697
> Fix custom parameter documentation

- MIGRATION_GUIDE.md
- README.md
We have added details on minimum supported iOS deployment version.
https://github.com/auth0/react-native-auth0/issues/698
> Add details about minimum supported iOS version

- MIGRATION_GUIDE.md
- README.md
Fixed migration guide to add update to build.gradle
Added migration guide notice to README
https://github.com/auth0/react-native-auth0/issues/704
> Fix migration guide to add Android Callback URL in `build.gradle`

- src/hooks/auth0-context.ts
`hasValidCredentials` only requires an optional parameter. This is update in the type declaration to reflect the same.
https://github.com/auth0/react-native-auth0/issues/711
> Make `hasValidCredentials` parameter optional

- .circleci/config.yml
This PR updates the CircleCI config to remove the test and Codecov steps, now that the build & test workflows have been migrated to GitHub Actions.
The remaining CircleCI config pertaining to package publishing was left in place, as it uses our CircleCI orb, which hasn't been updated to use GitHub Actions yet.
> Remove CircleCI tests config

- .github/dependabot.yml
This PR sets up Dependabot to check for updates of the GitHub actions in use, which are pinned to a specific SHA.
> Use Dependabot to update GH actions

- .github/workflows/main.yml
This PR fixes the `cancel-in-progress` concurrency config in the GH Actions workflow. Given that the workflow is only configured to run on pull requests, the previous configuration does not really apply.
> Fix `cancel-in-progress` in GH Actions workflow

- .github/dependabot.yml
Adds back dependabot configuration for npm.
> Add back dependabot config for npm

- android/build.gradle
We are updating Auth0.Android which has transitive dependency to okio from OkHttp to fix https://github.com/advisories/GHSA-w33c-445m-f8w7.
> Update Auth0.Android to resolve CVE-2023-3635

- android/src/main/java/com/auth0/react/A0Auth0Module.java
With this change, we will add error description to our error message similar to iOS. This will allow users to get custom error sent through actions in server.
https://github.com/auth0/react-native-auth0/issues/749
Local Testing
```
{"nativeStackAndroid":[{"lineNumber":202,"file":"OAuthManager.kt","methodName":"assertNoError","class":"com.auth0.android.provider.OAuthManager"},{"lineNumber":95,"file":"OAuthManager.kt","methodName":"resume","class":"com.auth0.android.provider.OAuthManager"},{"lineNumber":77,"file":"WebAuthProvider.kt","methodName":"resume","class":"com.auth0.android.provider.WebAuthProvider"},{"lineNumber":94,"file":"AuthenticationActivity.kt","methodName":"deliverAuthenticationResult$auth0_release","class":"com.auth0.android.provider.AuthenticationActivity"},{"lineNumber":58 …
```
> Provide error description in android

- .github/workflows/main.yml
- .github/workflows/snyk.yml
This PR:
- Fixes an issue with the Snyk workflow referencing an incorrect language type.
- Updates the `main` build workflow to have greater specificity in its concurrency group.
N/A
N/A
> ci: Update Workflows

- src/types.ts
Fixes the `user_metadata` type `CreateUserOptions` to accept an object instead of string
https://github.com/auth0/react-native-auth0/issues/758
I have tested the changes manually
> Fix metadata type in `CreateUserOptions`

- ios/NativeBridge.swift
- src/credentials-manager/index.ts
Previously we were not passing `parameters` when `forceRefresh` was true **only in iOS**. We are fixing this issue by passing this value along to the native layer.
There has been internal requests to fix this issue
We have done manual tests. We couldn't write unit tests as the native layer is currently not covered by our unit tests.
> Support additional parameters for forceRefresh in iOS

- .github/actions/publish-package/action.yml
Remove build action as publish does it automatically and the action is missing
https://github.com/auth0/react-native-auth0/actions/runs/7129536408/job/19413827588
> Remove build package as publish does it automatically

- .snyk
- package-lock.json
- package.json
- Bumped up version of expo to 51.0.24 & react-native to 0.74.4 to fix snyk vulnerabilities
- Ignored Snyk Vulnerabilities without solutions
https://github.com/auth0/react-native-auth0/pull/936
> chore: bumped up version of expo to 51.0.24 & react-native to 0.74.4 to fix snyk vulnerabilities

- package.json
Creating seperate PR for #1037 due to issues in Github organizational setup. Credits goes to @guabu for contributing this for us.
This PR removes the `codegenConfig` which was caused builds to fail when running under the new architecture. This is also inline with the reactwg recommendation:
> If you have already added a Codegen spec to your library, but the library is not fully converted to TurboModules/Fabric, we recommend that you delete it before proceeding. You can add this back when you are ready to convert your library to natively use TurboModules/Fabric without the Interop Layer.
The changes have been tested with a sample app using the following React Native versions:
* 0.77.0
* 0.76
* 0.70.15
A follow-up PR will contain a complete migration to Turbo Modules. …
> fix: Interop Layer 

- README.md
- android/build.gradle
- example/android/app/build.gradle
- example/android/app/src/main/java/com/auth0example/MainApplication.java
- example/android/build.gradle
- Upgraded the version of the underlying [android:auth0](https://github.com/auth0/Auth0.Android/releases/tag/3.2.1) sdk version to `v3.2.1`
- Refer [github-issue](https://github.com/facebook/react-native/issues/41288) for more details on the changes done to fix the errors observed on upgrade to Android 34.
- Fixes #1038
> Update android sdk version to v3.2.1

- src/auth/__tests__/__snapshots__/index.spec.js.snap
- src/auth/__tests__/index.spec.js
- src/hooks/__tests__/use-auth0.spec.jsx
- src/hooks/auth0-context.ts
- src/hooks/auth0-provider.tsx
- src/hooks/use-auth0.ts
- src/types.ts
- The userProfile field in ExchangeNativeSocialOptions is now a string. Fixes : #852 
- Adds hook methods to the following : (building on the contribution from [mnemitz](https://github.com/mnemitz) in #1023 )
- `revokeRefreshToken` :  exposes the method for revoking refresh tokens
- `authorizeWithExchangeNativeSocial` : exposes the hook method for a Native social exchange
- [SDK-5566](https://auth0team.atlassian.net/browse/SDK-5566)
- #1023 
- #852 
[SDK-5566]: https://auth0team.atlassian.net/browse/SDK-5566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixes type issue in ExhangeNativeSocial - Adds hook methods for exchangeNativeSocial and revoke

- example/android/build.gradle
- src/hooks/auth0-context.ts
- src/hooks/auth0-provider.tsx
- Adds support for resetPassword via hooks.
- [SDK-5644](https://auth0team.atlassian.net/browse/SDK-5644)
[SDK-5644]: https://auth0team.atlassian.net/browse/SDK-5644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add hooks support for resetPassword

- README.md
- android/src/main/java/com/auth0/react/A0Auth0Module.java
- src/credentials-manager/__tests__/credentials-manager.spec.js
- src/credentials-manager/credentialsManagerError.ts
- src/credentials-manager/index.ts
- src/hooks/auth0-context.ts
- src/hooks/reducer.ts
- src/utils/baseError.ts
We now expose platform agnostic generic error codes that represent different exception scenarios common in both android and iOS. 
We have considered only the `CredentialsManagerError` for now. 
Keeping the backward compatibility in mind, a new field with the generic error code has been exposed via the `BaseError` class.
The users can leverage the field as below : 
```js
try {
const credentials = await auth0.credentialsManager.getCredentials();
} catch (error) {
if(error.generic_error_code == "NO_CREDENTIALS"){
// handle scenario
}
}
```
**Note** : The old behaviour still remains untouched. 
- The changes partially address the ask in #923 
- [SDK-5643](https://auth0team.atlassian.net/browse/SDK-5643)
[SDK-5643]: https://auth0team.atlassian.net/browse/SDK-5643?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
> Expose generic error codes for CredentialsManagerError

- README.md
- src/utils/__tests__/addDefaultLocalAuthOptions.spec.js
- src/utils/addDefaultLocalAuthOptions.ts
- Updated the deviceCredentialFallback property within the LocalAuthenticationOptions interface to default to false.
- Revised the SDK documentation to reflect the new default value of the deviceCredentialFallback property.
- GitHub Issue: [#980](https://github.com/auth0/react-native-auth0/issues/980)
> Added deviceCredentialFallback default value

- .snyk
- src/hooks/auth0-provider.tsx
- feat: add optional timeout prop to Auth0Provider for authentication requests
> feat: add optional timeout prop to Auth0Provider for authentication requests

- .github/workflows/main.yml
- EXAMPLES.md
- README.md
- src/auth/__tests__/index.spec.js
- src/auth/index.ts
- src/auth0.ts
- src/hooks/__tests__/use-auth0.spec.jsx
- src/hooks/auth0-provider.tsx
- src/management/users.ts
- src/networking/__tests__/index.spec.js
- src/networking/index.ts
- src/types.ts
This PR adds support for custom headers in the React Native Auth0 SDK, allowing developers to include custom headers in API requests for both global and per-request scenarios.
Key changes include:
- Added a new `headers` property to the `Auth0Options` interface to support global headers across all requests
- Modified the `Auth0` constructor to store and pass headers to the Auth instance
- Updated the `Auth` class to accept headers at initialization and in various methods
- Added support for per-request custom headers that can override global headers
- Added `headers` property to the `Auth0Provider` component for React hooks integration
- Methods including `passwordRealm`, `userInfo`, `refreshToken` and others now accept custom headers parameter
This change provides developers with greater …
> feat: Add support for custom headers

- package.json
This PR fixes issue #1081 where Expo users were experiencing an error with our config plugin: "Unexpected token 'typeof'" when running `expo install react-native-auth0` or `expo prebuild`.
The root cause is related to how react-native-builder-bob now generates package.json files inside the lib/*/ directories. This breaks Expo's plugin system because the `findUpPlugin` function (responsible for locating the nearest package.json) stops at the lib/commonjs directory instead of finding our root package.json.
Changes made:
- Modified the `prepare` script in package.json to remove the automatically generated package.json files in lib directories:
```
"prepare": "bob build && rm -rf lib/*/package.json"
```
- Updated dependencies to ensure compatibility with the latest versions of …
> fix: Update prepare script to clean up package.json files

- README.md
- Updated Swift AppDelegate setup instructions for iOS
-  Clarified platform compatibility details
> docs: Update setup guide for ios and platform compatibility in README.md

- MIGRATION_GUIDE.md
- README.md
**Added**
- Upgrade SDK to React Native 0.79.2 and Add Support for Expo SDK 53 [\#1147](https://github.com/auth0/react-native-auth0/pull/1147) ([subhankarmaiti](https://github.com/subhankarmaiti))
**Changed**
- docs: Update setup guide for ios and platform compatibility in README.md [\#1170](https://github.com/auth0/react-native-auth0/pull/1170) ([subhankarmaiti](https://github.com/subhankarmaiti))
> Release v5.0.0-beta.1

- android/src/main/java/com/auth0/react/A0Auth0Module.java
This PR fixes [issue #1186](https://github.com/auth0/react-native-auth0/issues/1186) where the `getBundleIdentifier()` function was inconsistently implemented across platforms.
- Corrected Android implementation to properly use the Promise pattern
- Verified iOS implementation was already correctly implemented
- Ensured both platforms return bundle identifiers consistently via Promises
This change ensures JavaScript code can reliably access bundle identifiers through a consistent Promise-based API across both iOS and Android platforms.
> Fix: getBundleIdentifier Implementation

- example/Gemfile.lock
- ios/A0Auth0.mm
This PR addresses critical issues that were preventing successful builds for users on iOS:
1. Enhanced Swift header imports in A0Auth0.mm to work correctly with static frameworks. The implementation now uses preprocessor directives to check for the header file in different locations:
- First tries importing from the module path `<A0Auth0/A0Auth0-Swift.h>`
- Falls back to the local import `"A0Auth0-Swift.h"` if the module import is not available
- Fixes #1180
- Fixes #986
- Verified that pod installation works successfully with the updated bundler version
- Confirmed that builds complete successfully in projects using static frameworks
> Fixed iOS Build Issues with Static Frameworks
