- android/src/main/java/com/auth0/react/A0Auth0Module.java
> Avoid crash with missing hide method

- README.md
Hey there,
Thanks for this great platform. I just found a typo in the readme, hope it helps 👍
> yarn install should be in production dependencies

- ios/A0Auth0.m
- webauth/agent.js
> Call resolve on logout load

- .gitignore
- webauth/__mocks__/auth0.js
- webauth/__mocks__/linking.js
- webauth/__mocks__/react-native.js
- webauth/__tests__/__snapshots__/agent.spec.js.snap
- webauth/__tests__/agent.spec.js
- webauth/agent.js
> Return error if native module is not linked

- README.md
follow up on https://github.com/auth0/react-native-auth0/issues/145
> Clarify redirect URI scheme format

- .circleci/config.yml
> Specify commit sha for codecov, and exit with 1 if not successful

- .circleci/config.yml
Makes use of our script to publish to npm/github when a new release PR is done.
> Automate package publishing

- DEVELOPMENT.md
The DEVELOPMENT.md documentation to provide proper guidance on testing in the local machine
The commands provided in the document have been tested on local machine manually
> Update DEVELOPMENT.md documentation

- README.md
Please describe both what is changing and why this is important. Include:
The code on passwordless SMS login needed an update due to referring email instead of phone number
https://github.com/auth0/react-native-auth0/issues/473
> Passwordless SMS documentation update

- .circleci/config.yml
- CHANGELOG.md
- docs/Auth.html
- docs/Auth0.html
- docs/CredentialsManager.html
- docs/WebAuth.html
- docs/auth0.js.html
- docs/auth_index.js.html
- docs/credentials-manager_index.js.html
- docs/global.html
- docs/hooks_auth0-provider.js.html
- docs/hooks_use-auth0.js.html
- docs/index.html
- docs/management_users.js.html
- docs/webauth_index.js.html
- package.json
- src/networking/telemetry.js
**Added**
- Add Expo config plugin (SDK 41+) [\#424](https://github.com/auth0/react-native-auth0/pull/424) ([sdacunha](https://github.com/sdacunha))
- [SDK-3591] New Hook API supporting login and logout [\#500](https://github.com/auth0/react-native-auth0/pull/500) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-3537] Credential manager for React Native [\#501](https://github.com/auth0/react-native-auth0/pull/501) ([poovamraj](https://github.com/poovamraj))
**Changed**
- Update peer dependency for React [\#509](https://github.com/auth0/react-native-auth0/pull/509) ([poovamraj](https://github.com/poovamraj))
[SDK-3591]: https://auth0team.atlassian.net/browse/SDK-3591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDK-3537]: …
> Release v2.14.0-fa.0

- index.ts
- src/auth/auth0Error.ts
- src/auth/authError.ts
- src/auth/index.ts
- src/auth0.ts
- src/credentials-manager/credentialsManagerError.ts
- src/credentials-manager/index.ts
- src/credentials-manager/localAuthenticationStrategy.ts
- src/hooks/auth0-context.ts
- src/hooks/auth0-provider.tsx
- src/hooks/reducer.ts
- src/hooks/use-auth0.ts
- src/internal-types.ts
- src/jwt/validator.ts
- src/management/error.ts
- src/management/users.ts
- src/networking/index.ts
- src/networking/telemetry.ts
- src/types.ts
- src/webauth/index.ts
This PR cleans up code documentation better suited for TypeDoc. Mainly moving parameter docs from one place to another, and filling out missing documentation where it was missing.
Also cleans up some types here and there (see comments).
ℹ️  **Note for reviewer**: There are a lot of whitespace changes introduced by automatic Prettier formatting; you can reduce the size of the PR by turning off whitespace changes.
> [SDK-4356] Documentation fixes

- .circleci/config.yml
- .shiprc
- codecov.yml
Making config changes to v3 beta release
> v3 Release prep

- .circleci/config.yml
- package.json
This change adds the missing index file that is required for the package to be imported in other projects
> Add missing index file from packing

- .circleci/config.yml
This PR includes the missing index file required to import the project. Please refer to the [CHANGELOG.md](https://github.com/auth0/react-native-auth0/blob/vnext/CHANGELOG.md) and [MIGRATION_GUIDE.md](https://github.com/auth0/react-native-auth0/blob/vnext/MIGRATION_GUIDE.md) for actual information on the project
> Release v3.0.0-beta.1

- README.md
Update README to add release announcement
> V3 beta release announcement

- CHANGELOG.md
- package.json
[Full Changelog](https://github.com/auth0/react-native-auth0/compare/v3.0.0-beta.2...v3.0.0-beta.3)
**Added**
- Export types as part of root [\#649](https://github.com/auth0/react-native-auth0/pull/676) ([poovamraj](https://github.com/poovamraj))
> Release v3.0.0-beta.3

- typedoc.json
Updating file to point for docs to be generated
> Update docs src file

- FAQ.md
- README.md
> Update RedirectActivity in README and FAQ

- .github/workflows/main.yml
This PR adds a workflow for running the existing tests (JS tests) using GitHub Actions. The CircleCI configuration will be removed in a follow-up PR.
> Add GH actions workflow for testing [SDK-4456]

- README.md
Use correct extension for light mode logo
> Fix logo in footer

- .github/actions/publish-package/action.yml
This PR should resolve the NPM publishing workflow error around the `shell` propery.
N/A
N/A
> fix: Resolve issue with NPM Publishing Workflow

- .github/workflows/release.yml
Added a missing condition to trigger the flow manually
> Add condition to release workflow to be triggered manually

- .github/actions/publish-package/action.yml
Replace NPM with Yarn commands for publish workflow
> Replace NPM with Yarn commands

- .github/actions/publish-package/action.yml
Fix yarn publish issue in auth
> Fix yarn publish authentication issue

- README.md
> Updated Readme recommending App links
